#!/bin/bash
# Copyright 2024 by Alan Munn
# MIT Licence (see README.md)
ls -t $(
for file in *.png; do
  output_file="$1$(( ++number )).png"
 mv "$file" $output_file
done) > /dev/null
echo "File count =  `ls *.png | wc -l`"